version: '3'
services:

    #PHP Service
    app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
        image: php:8.0.26-apache
        container_name: mylaravel
        restart: unless-stopped

        ports:
            - 8084:80
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            LARAVEL_SAIL: 1
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8083:80
        environment:
            - PMA_ARBITRARY=1
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8082:80"
            - "8443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:latest
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: mylaravel
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
